import React from 'react';
import './AboutUs.css';

const AboutUs = () => {
  return (
    <section id="about" className="about-section">
      <div className="about-container">
        <div className="about-image">
          <img src="/about-us.jpeg" alt="Football School Students" />
        </div>
        <div className="about-content">
          <h1>WELCOME TO THE TECHNO INDIA MANCHESTER CITY FOOTBALL SCHOOL!</h1>
          <p>
            Where passion meets professional excellence. In collaboration with the renowned <strong>City Football Group</strong>, our Kolkata academy is set to revolutionize football in India for children aged 3 to 17 years.
          </p>
          <p>
            Equipped with state-of-the-art facilities, the school is led by certified <strong>Manchester City coaches</strong>, offering world-class training and international expertise. Exceptional players may even have the opportunity to train at Manchester City's UK facilities for greater exposure and development.
          </p>
          <p>
            Progress is tracked with comprehensive performance reports and personalised improvement plans, directly generated by <strong>Manchester City Football School</strong> in the UK. Leveraging advanced sports technology, these reports refine skills, enhance tactical understanding, and shape the future of aspiring footballers.
          </p>
          <button className="read-more-btn">
            <span>Read More</span>
          </button>
        </div>
      </div>
    </section>
  );
};

export default AboutUs;
